# Generated by Django 2.2.11 on 2020-05-02 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ResearchPaper', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='research_papers',
            new_name='research_paper',
        ),
    ]
