# Generated by Django 2.2.11 on 2020-05-02 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200408_0925'),
        ('ResearchPaper', '0002_auto_20200502_1123'),
    ]

    operations = [
        migrations.AddField(
            model_name='research_paper',
            name='authors',
            field=models.ManyToManyField(to='users.Profile_student'),
        ),
    ]
