# Generated by Django 2.2.11 on 2020-05-02 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200408_0925'),
        ('ResearchPaper', '0003_research_paper_authors'),
    ]

    operations = [
        migrations.CreateModel(
            name='paper_tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=15, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='research_paper',
            name='liked_by',
            field=models.ManyToManyField(to='users.Profile_student'),
        ),
        migrations.AlterField(
            model_name='research_paper',
            name='authors',
            field=models.ManyToManyField(related_name='researchpaper_research_paper_related', related_query_name='researchpaper_research_papers', to='users.Profile_student'),
        ),
        migrations.AddField(
            model_name='research_paper',
            name='tags',
            field=models.ManyToManyField(to='ResearchPaper.paper_tag'),
        ),
    ]
