# Generated by Django 2.2.11 on 2020-05-09 19:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ResearchPaper', '0004_auto_20200502_1224'),
    ]

    operations = [
        migrations.AddField(
            model_name='research_paper',
            name='created_on',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
